version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/101413667_comp3123_assignment2_reactjs
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000

  backend:
    build:
      context: ./backend/101413667_COMP3123_Assignment1_NodeJs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    volumes:
      - ./backend/101413667_COMP3123_Assignment1_NodeJs:/app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge
